sudo: required
services:
  - docker
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
env:
  - TASK=test
  - TASK=lint
before_install:
  - npm i -g npm 
  - npm -global install lerna
  
install:
  - npm install
  - npm run bootstrap
  - npm run build:apps
  - npm run publish:apps 
before_script:
  - npm prune
script:
  - npm run $TASK
after_success:
  - ./node_modules/.bin/lcov-result-merger 'apps/*/coverage/lcov.info' | ./node_modules/.bin/coveralls
